#import "@/queries/building-blocks/graphql/fragments/basic-media.gql"

query QUERY_HEADER_BY_ID($id: String!, $isPreview: Boolean!) {
  componentHeader(id: $id, preview: $isPreview) {
    headerName
    headerLogo {
      ...BasicMediaFragment
    }
  }
}
