import "@/app/assets/styles/globals.css";
import MainFooter from "@/components/component-blocks/footer/footer";
import MainHeader from "@/components/component-blocks/header/header";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { ContentfulDataService } from "@/lib/services/contentful-data-service";
import { TypeComponentFooter, TypeComponentHeader } from "@/lib/types";
import QUERY_FOOTER_BY_ID from "@/queries/component-blocks/graphql/footer.gql";
import QUERY_HEADER_BY_ID from "@/queries/component-blocks/graphql/header.gql";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"]
});

type HeaderDataProps = {
  componentHeader: TypeComponentHeader;
};

type FooterDataProps = {
  componentFooter: TypeComponentFooter;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerData: HeaderDataProps = await ContentfulDataService.fetchDataById(
    QUERY_HEADER_BY_ID,
    "7lzzftwTe28V0LLUOWx0bz"
  );
  const footerData: FooterDataProps = await ContentfulDataService.fetchDataById(
    QUERY_FOOTER_BY_ID,
    "sUGa0cOvu2oyVuDVyr663"
  );

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${outfit.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header>
            <MainHeader data={headerData.componentHeader} />
          </header>
          {children}
          <footer>
            <MainFooter data={footerData.componentFooter} />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
